### ISSUE TITLE
Document background color not taken into account for SVG

### ISSUE THREAD

**Issue by myselfhimself** [StefanTraistaru/batch-export#10]
Hello thanks for this very good plugin.

When exporting layers to PNG, the document's background color, when non-transparent, is still interpreted as transparent in the output PNGs.
Example of output with transparent PNG background despite non-transparent source Inkscape SVG background.
![youwin-02](https://user-images.githubusercontent.com/1265346/107863279-5443c300-6e53-11eb-87dd-d6618d950edd.png)

How to reproduce:
- download and open this SVG file: [youwin_spritesheet.zip](https://github.com/StefanTraistaru/batch-export/files/5976665/youwin_spritesheet.zip)
- use current master branch plugin
- delete the the '[fixed] background' layer
- export to PNG at 884 x 497 defined size
- notice a transparent background in each exported file

Circumventing way:
- create a '[fixed] Background' layer as stated in the README, and tick the 'Use background layers' checkbox before export.

About: Used for p5js video game https://github.com/myselfhimself/BerlinWallBreaker/ for the You Win last screen's sprites

**Comment by myselfhimself** [comment]
Tested on Ubuntu Linux 20.04 or so

**Comment by StefanTraistaru** [comment]
> When exporting layers to PNG, the document's background color, when non-transparent, is still interpreted as transparent in the output PNGs.
> Example of output with transparent PNG background despite non-transparent source Inkscape SVG background.

I am really sorry but I do not understand the problem you are describing here. I tried reproducing it but I didn't see any unexpected behavior so I'm having a hard time trying to figure out what to look for.

I would appreciate if:
1. You could reproduce the problem with logging turned on (you can find this option on the Help tab) and send that log here. You can open the log with any text editor if you want to look inside before posting it. It will display the extension current settings and data from the Inkscape svg file you are exporting (the only personal thing that would show there would be the path where the output files are exported and the log path; feel free to censor those). 
2. You can describe specifically using a file (the one you have sent or a simpler one - maybe containing only one layer) what the output is compared to what are you expecting it to be. (You can even color on the output png highlighting the problem in a program la paint) 

Finally, I don't want to sound condescending, but are you sure there is a problem with the extension?
The extension only performs multiple export operations instead of you doing it manually. That means that you can create a file with only one layer and manually export it from Inkscape (without using my extension). If the problem persists there may be a problem with Inkscape itself or with how you think the export should be compared to how it actually is.
