### ISSUE TITLE
Controls Tab Missing Options

### ISSUE THREAD

**Issue by ejdprops** [StefanTraistaru/batch-export#11]
Just installed tis extension but the Controls Tab is missing options and when I try to run it, I get an error.
![image](https://user-images.githubusercontent.com/47348053/113483171-b25e5100-9467-11eb-91ee-66510441843e.png)
![image](https://user-images.githubusercontent.com/47348053/113483196-d4f06a00-9467-11eb-8f9f-4e14c852d2be.png)

**Comment by StefanTraistaru** [comment]
From the screenshots you provided it seems that the extension files might be corrupted, maybe some lines are missing.
1. Can you check that the files: "**batch_export.inx**" and "**batch_export.py**" that you have copied in the extensions folder are the same with the ones from this repository?
2. A sure way to check if they are unchanged is to uninstall the extension and install it again. 
    - Simply delete the 2 files from the inkscape extensions folder (_make sure that there are no other files named "batch_export.inx" or "batch_export.py" in this folder and be careful to not delete any other files as you can break/delete other extensions you have installed_)
    - download the extension again
    - copy the 2 files ("**batch_export.inx**" and "**batch_export.py**") in the inkscape extension folder.


Let me know if it works after you do this.

**Comment by ejdprops** [comment]
Stefan,   I followed the steps provided and there was no change.  The controls are still showing the same as before.  I verified the files were the same as on the repository.   Thanks for your help. Evan Sent from Mail for Windows 10 From: Stefan TraistaruSent: Sunday, April 4, 2021 7:11 AMTo: StefanTraistaru/batch-exportCc: ejdprops; AuthorSubject: Re: [StefanTraistaru/batch-export] Controls Tab Missing Options (#11) From the screenshots you provided it seems that the extension files might be corrupted, maybe some lines are missing.Can you check that the files: "batch_export.inx" and "batch_export.py" that you have copied in the extensions folder are the same with the ones from this repository?A sure way to check if they are unchanged is to uninstall the extension and install it again. Simply delete the 2 files from the inkscape extensions folder (make sure that there are no other files named "batch_export.inx" or "batch_export.py" in this folder and be careful to not delete any other files as you can break/delete other extensions you have installed)download the extension againcopy the 2 files ("batch_export.inx" and "batch_export.py") in the inkscape extension folder.Let me know if it works after you do this.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by StefanTraistaru** [comment]
Ok, so for the next part I will need more details from you.

1. What operating system are you running? (From the screenshots I assume it is Windows 10)
2. What version of Inkscape are you using? (Help->About Inkscape)
3. Are there any other tabs that are missing options, apart from the Controls Tab you mentioned above?
4. Can you use the extension with the logging option enabled and upload the log file so I can have a look at it?
   - Go to the Help Tab
   - Tick the option "use logging"
   - Select a path for the log file

I assumed you are using Windows 10, so I created a virtual machine with a fresh Windows 10 install. I installed Inkscape and then the extension and everything worked. So I believe this may be an error on your end. I hope these new details will help us to discover what the problem is.

P.S. It would be great if you respond directly here on Github, as the mail reply seems to create many unwanted characters (html artifacts).
