### ISSUE TITLE
Export fail when layer are too big

### ISSUE THREAD

**Issue by KBillel** [StefanTraistaru/batch-export#14]
Hi,

I have some trouble when exporting layers that are big.

Here is the SVG : [SVG FILE](https://ufile.io/hnpqu3qu)
Here is the log file :  [batch_export.log](https://github.com/StefanTraistaru/batch-export/files/7117329/batch_export.log)

If I try to export Layer 1 it will crash. Other layers are fine. I checked that the tmp file was create and there is no problem on this side.

I've try to export as PDF1.4 and PDF 1.5 and I have the same issue
I also notice an inkscape process that get stuck and seems to do nothing :
![image](https://user-images.githubusercontent.com/36503635/132249897-72c9d8f0-bd41-4c89-a04b-64d88ca07eca.png)

After some further testing, it seems that this is not related to the size of the Layer as I could export a Layer that was 3mb while the Layer 1 in my example file should not exceed 1mb.

Edit : After some more testing. Once the process is stuck, I tried to manually run the Inkscape command given by the log file. And it is working. I have no idea why the first execution of the command would get stuck ? 

Thank you very much for the 

Billel

**Comment by StefanTraistaru** [comment]
Good find.

Can you please modify line 319 from batch_export.py:
```py
with subprocess.Popen(command, stdout=subprocess.PIPE, stderr=subprocess.PIPE) as proc:
```
with this one:
```py
with subprocess.Popen(command) as proc:
```

**This fixed the export function for me and I want to know if it does the same to you**. 

The problem was a deadlock that was occurring if the buffer from stdout and stderr  fill up and block the child process.

> Edit : After some more testing. Once the process is stuck, I tried to manually run the Inkscape command given by the log file. And it is working. I have no idea why the first execution of the command would get stuck ?

After I ran the command in the terminal, I saw a lot of warnings like this one: `Inkscape currently only supports color-interpolation = sRGB`. I think this is the culprit that causes the issue.

P.S. Now all those warning message will appear in a new Inkscape info window, but the extension won't crash and the export will function correctly.

**Comment by KBillel** [comment]
Hey Stefan,
Sorry I did not get any notification

You fix is working perfectly. Thank you so much !

Billel

**Comment by StefanTraistaru** [comment]
I forgot to post a comment.

The update is now available on the master branch and on the Inkscape website. No need to modify any lines of code yourself.
