### ISSUE TITLE
Clones are invisible after batch export

### ISSUE THREAD

**Issue by BaronFalke** [StefanTraistaru/batch-export#7]
Clones of objects are not exported, only their original source are exported.
This way of all my 8 layers only the first one shows all objects. The other layers do not
contain the cloned objects from the first layer.

**Comment by StefanTraistaru** [comment]
I am fairly new to Inkscape and this is the first time I played with the clone feature (it's really cool and time saving so thank you for showing it to me). I replicated your issue and that does seem to be the case. The problem is linked with the way the clones are handled in Inkscape and how my extension exports each layer into a file of **minimum** size (for SVG at least; you can read the RESULT section in the Readme for further details).

I will look how to manage this usecase in the extension, but untill then you can use this workaround. I managed to successfully export the files using this method:

1. Create a copy of your Inkscape file so that you don't mess with your file. (Or simply create a backup as this will break your clones)
2. Select all objects (`Ctrl+Alt+A` or `Edit->Select All in All Layers` should work if there are no locked layers) and use the option `Edit->Clone->Unlink Clones recursively`.
3. Use the extension as previously intended.

I repeat, this method (specifically step 2) will break your clones so make sure you have a **backup**.

I will update this issue if I can solve this problem in the extension itself.

**Comment by StefanTraistaru** [comment]
I added support for exporting files which contain clones. You can find a new option in the "Controls" panel. You can find details in the Readme file.
Could you try it out and tell me if it works for you as well?

P.S.
I still recommend using the method I mentioned in my last comment, as it will result in lower file sizes (for SVG files at least):
> 1. Create a copy of your Inkscape file so that you don't mess with your file. (Or simply create a backup as this will break your clones)
> 2. Select all objects (Ctrl+Alt+A or Edit->Select All in All Layers should work if there are no locked layers) and use the option Edit->Clone->Unlink Clones recursively.
> 3. Use the extension as previously intended.
